services:
  - type: web
    name: ytdl
    env: node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
